### ISSUE TITLE
Check and prevent stack over- and under-flow

### ISSUE THREAD

**Issue by ybank** [ybank/dsproj#1]
When the stack is empty, popping will cause underflow; when the stack is full, pushing will cause overflow. The stack should check the potential out-of-bound access and prevent it.

**Comment by ybank** [comment]
Prevented over- and under-flow of stacks. 

Ready to review [here](http://sosa05.ucsd.edu:8000/sema.diff.html).

**Comment by csi-reviewer** [comment]
There are two problems:
1. The pop method seems only tested for stacks with default capacity.
2. No exceptional invariants for pop - expecting exception thrown when popping an empty stack.

**Comment by ybank** [comment]
Thanks for the insightful review comments! I have updated my implementation so it should be good now. Could you please review it [here](http://sosa05.ucsd.edu:8001/sema.diff.html)?

**Comment by csi-reviewer** [comment]
LGTM!
